// Decompiled with JetBrains decompiler
// Type: Org.BouncyCastle.Crypto.Engines.SerpentEngine
// Assembly: BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942
// MVID: 2C1E8153-B25B-4CDE-9676-EEDAF8A00392
// Assembly location: C:\Users\MÜRVET YÜZDEN ŞEN\Downloads\BouncyCastle.Crypto.dll

using Org.BouncyCastle.Crypto.Utilities;
using System;

namespace Org.BouncyCastle.Crypto.Engines
{
    public sealed class SerpentEngine : SerpentEngineBase
    {
        protected override int[] MakeWorkingKey( byte[] key )
        {
            int[] sourceArray = new int[16];
            int num = 0;
            int off;
            for (off = 0; off + 4 < key.Length; off += 4)
                sourceArray[num++] = (int)Pack.LE_To_UInt32( key, off );
            if (off % 4 != 0)
                throw new ArgumentException( "key must be a multiple of 4 bytes" );
            int[] numArray = sourceArray;
            int index1 = num;
            int index2 = index1 + 1;
            int uint32 = (int)Pack.LE_To_UInt32( key, off );
            numArray[index1] = uint32;
            if (index2 < 8)
                sourceArray[index2] = 1;
            int length = 132;
            int[] destinationArray = new int[length];
            for (int index3 = 8; index3 < 16; ++index3)
                sourceArray[index3] = RotateLeft( sourceArray[index3 - 8] ^ sourceArray[index3 - 5] ^ sourceArray[index3 - 3] ^ sourceArray[index3 - 1] ^ -1640531527 ^ (index3 - 8), 11 );
            Array.Copy( sourceArray, 8, destinationArray, 0, 8 );
            for (int index4 = 8; index4 < length; ++index4)
                destinationArray[index4] = RotateLeft( destinationArray[index4 - 8] ^ destinationArray[index4 - 5] ^ destinationArray[index4 - 3] ^ destinationArray[index4 - 1] ^ -1640531527 ^ index4, 11 );
            this.Sb3( destinationArray[0], destinationArray[1], destinationArray[2], destinationArray[3] );
            destinationArray[0] = this.X0;
            destinationArray[1] = this.X1;
            destinationArray[2] = this.X2;
            destinationArray[3] = this.X3;
            this.Sb2( destinationArray[4], destinationArray[5], destinationArray[6], destinationArray[7] );
            destinationArray[4] = this.X0;
            destinationArray[5] = this.X1;
            destinationArray[6] = this.X2;
            destinationArray[7] = this.X3;
            this.Sb1( destinationArray[8], destinationArray[9], destinationArray[10], destinationArray[11] );
            destinationArray[8] = this.X0;
            destinationArray[9] = this.X1;
            destinationArray[10] = this.X2;
            destinationArray[11] = this.X3;
            this.Sb0( destinationArray[12], destinationArray[13], destinationArray[14], destinationArray[15] );
            destinationArray[12] = this.X0;
            destinationArray[13] = this.X1;
            destinationArray[14] = this.X2;
            destinationArray[15] = this.X3;
            this.Sb7( destinationArray[16], destinationArray[17], destinationArray[18], destinationArray[19] );
            destinationArray[16] = this.X0;
            destinationArray[17] = this.X1;
            destinationArray[18] = this.X2;
            destinationArray[19] = this.X3;
            this.Sb6( destinationArray[20], destinationArray[21], destinationArray[22], destinationArray[23] );
            destinationArray[20] = this.X0;
            destinationArray[21] = this.X1;
            destinationArray[22] = this.X2;
            destinationArray[23] = this.X3;
            this.Sb5( destinationArray[24], destinationArray[25], destinationArray[26], destinationArray[27] );
            destinationArray[24] = this.X0;
            destinationArray[25] = this.X1;
            destinationArray[26] = this.X2;
            destinationArray[27] = this.X3;
            this.Sb4( destinationArray[28], destinationArray[29], destinationArray[30], destinationArray[31] );
            destinationArray[28] = this.X0;
            destinationArray[29] = this.X1;
            destinationArray[30] = this.X2;
            destinationArray[31] = this.X3;
            this.Sb3( destinationArray[32], destinationArray[33], destinationArray[34], destinationArray[35] );
            destinationArray[32] = this.X0;
            destinationArray[33] = this.X1;
            destinationArray[34] = this.X2;
            destinationArray[35] = this.X3;
            this.Sb2( destinationArray[36], destinationArray[37], destinationArray[38], destinationArray[39] );
            destinationArray[36] = this.X0;
            destinationArray[37] = this.X1;
            destinationArray[38] = this.X2;
            destinationArray[39] = this.X3;
            this.Sb1( destinationArray[40], destinationArray[41], destinationArray[42], destinationArray[43] );
            destinationArray[40] = this.X0;
            destinationArray[41] = this.X1;
            destinationArray[42] = this.X2;
            destinationArray[43] = this.X3;
            this.Sb0( destinationArray[44], destinationArray[45], destinationArray[46], destinationArray[47] );
            destinationArray[44] = this.X0;
            destinationArray[45] = this.X1;
            destinationArray[46] = this.X2;
            destinationArray[47] = this.X3;
            this.Sb7( destinationArray[48], destinationArray[49], destinationArray[50], destinationArray[51] );
            destinationArray[48] = this.X0;
            destinationArray[49] = this.X1;
            destinationArray[50] = this.X2;
            destinationArray[51] = this.X3;
            this.Sb6( destinationArray[52], destinationArray[53], destinationArray[54], destinationArray[55] );
            destinationArray[52] = this.X0;
            destinationArray[53] = this.X1;
            destinationArray[54] = this.X2;
            destinationArray[55] = this.X3;
            this.Sb5( destinationArray[56], destinationArray[57], destinationArray[58], destinationArray[59] );
            destinationArray[56] = this.X0;
            destinationArray[57] = this.X1;
            destinationArray[58] = this.X2;
            destinationArray[59] = this.X3;
            this.Sb4( destinationArray[60], destinationArray[61], destinationArray[62], destinationArray[63] );
            destinationArray[60] = this.X0;
            destinationArray[61] = this.X1;
            destinationArray[62] = this.X2;
            destinationArray[63] = this.X3;
            this.Sb3( destinationArray[64], destinationArray[65], destinationArray[66], destinationArray[67] );
            destinationArray[64] = this.X0;
            destinationArray[65] = this.X1;
            destinationArray[66] = this.X2;
            destinationArray[67] = this.X3;
            this.Sb2( destinationArray[68], destinationArray[69], destinationArray[70], destinationArray[71] );
            destinationArray[68] = this.X0;
            destinationArray[69] = this.X1;
            destinationArray[70] = this.X2;
            destinationArray[71] = this.X3;
            this.Sb1( destinationArray[72], destinationArray[73], destinationArray[74], destinationArray[75] );
            destinationArray[72] = this.X0;
            destinationArray[73] = this.X1;
            destinationArray[74] = this.X2;
            destinationArray[75] = this.X3;
            this.Sb0( destinationArray[76], destinationArray[77], destinationArray[78], destinationArray[79] );
            destinationArray[76] = this.X0;
            destinationArray[77] = this.X1;
            destinationArray[78] = this.X2;
            destinationArray[79] = this.X3;
            this.Sb7( destinationArray[80], destinationArray[81], destinationArray[82], destinationArray[83] );
            destinationArray[80] = this.X0;
            destinationArray[81] = this.X1;
            destinationArray[82] = this.X2;
            destinationArray[83] = this.X3;
            this.Sb6( destinationArray[84], destinationArray[85], destinationArray[86], destinationArray[87] );
            destinationArray[84] = this.X0;
            destinationArray[85] = this.X1;
            destinationArray[86] = this.X2;
            destinationArray[87] = this.X3;
            this.Sb5( destinationArray[88], destinationArray[89], destinationArray[90], destinationArray[91] );
            destinationArray[88] = this.X0;
            destinationArray[89] = this.X1;
            destinationArray[90] = this.X2;
            destinationArray[91] = this.X3;
            this.Sb4( destinationArray[92], destinationArray[93], destinationArray[94], destinationArray[95] );
            destinationArray[92] = this.X0;
            destinationArray[93] = this.X1;
            destinationArray[94] = this.X2;
            destinationArray[95] = this.X3;
            this.Sb3( destinationArray[96], destinationArray[97], destinationArray[98], destinationArray[99] );
            destinationArray[96] = this.X0;
            destinationArray[97] = this.X1;
            destinationArray[98] = this.X2;
            destinationArray[99] = this.X3;
            this.Sb2( destinationArray[100], destinationArray[101], destinationArray[102], destinationArray[103] );
            destinationArray[100] = this.X0;
            destinationArray[101] = this.X1;
            destinationArray[102] = this.X2;
            destinationArray[103] = this.X3;
            this.Sb1( destinationArray[104], destinationArray[105], destinationArray[106], destinationArray[107] );
            destinationArray[104] = this.X0;
            destinationArray[105] = this.X1;
            destinationArray[106] = this.X2;
            destinationArray[107] = this.X3;
            this.Sb0( destinationArray[108], destinationArray[109], destinationArray[110], destinationArray[111] );
            destinationArray[108] = this.X0;
            destinationArray[109] = this.X1;
            destinationArray[110] = this.X2;
            destinationArray[111] = this.X3;
            this.Sb7( destinationArray[112], destinationArray[113], destinationArray[114], destinationArray[115] );
            destinationArray[112] = this.X0;
            destinationArray[113] = this.X1;
            destinationArray[114] = this.X2;
            destinationArray[115] = this.X3;
            this.Sb6( destinationArray[116], destinationArray[117], destinationArray[118], destinationArray[119] );
            destinationArray[116] = this.X0;
            destinationArray[117] = this.X1;
            destinationArray[118] = this.X2;
            destinationArray[119] = this.X3;
            this.Sb5( destinationArray[120], destinationArray[121], destinationArray[122], destinationArray[123] );
            destinationArray[120] = this.X0;
            destinationArray[121] = this.X1;
            destinationArray[122] = this.X2;
            destinationArray[123] = this.X3;
            this.Sb4( destinationArray[124], destinationArray[125], destinationArray[126], destinationArray[sbyte.MaxValue] );
            destinationArray[124] = this.X0;
            destinationArray[125] = this.X1;
            destinationArray[126] = this.X2;
            destinationArray[sbyte.MaxValue] = this.X3;
            this.Sb3( destinationArray[128], destinationArray[129], destinationArray[130], destinationArray[131] );
            destinationArray[128] = this.X0;
            destinationArray[129] = this.X1;
            destinationArray[130] = this.X2;
            destinationArray[131] = this.X3;
            return destinationArray;
        }

        protected override void EncryptBlock( byte[] input, int inOff, byte[] output, int outOff )
        {
            this.X0 = (int)Pack.LE_To_UInt32( input, inOff );
            this.X1 = (int)Pack.LE_To_UInt32( input, inOff + 4 );
            this.X2 = (int)Pack.LE_To_UInt32( input, inOff + 8 );
            this.X3 = (int)Pack.LE_To_UInt32( input, inOff + 12 );
            this.Sb0( this.wKey[0] ^ this.X0, this.wKey[1] ^ this.X1, this.wKey[2] ^ this.X2, this.wKey[3] ^ this.X3 );
            this.LT();
            this.Sb1( this.wKey[4] ^ this.X0, this.wKey[5] ^ this.X1, this.wKey[6] ^ this.X2, this.wKey[7] ^ this.X3 );
            this.LT();
            this.Sb2( this.wKey[8] ^ this.X0, this.wKey[9] ^ this.X1, this.wKey[10] ^ this.X2, this.wKey[11] ^ this.X3 );
            this.LT();
            this.Sb3( this.wKey[12] ^ this.X0, this.wKey[13] ^ this.X1, this.wKey[14] ^ this.X2, this.wKey[15] ^ this.X3 );
            this.LT();
            this.Sb4( this.wKey[16] ^ this.X0, this.wKey[17] ^ this.X1, this.wKey[18] ^ this.X2, this.wKey[19] ^ this.X3 );
            this.LT();
            this.Sb5( this.wKey[20] ^ this.X0, this.wKey[21] ^ this.X1, this.wKey[22] ^ this.X2, this.wKey[23] ^ this.X3 );
            this.LT();
            this.Sb6( this.wKey[24] ^ this.X0, this.wKey[25] ^ this.X1, this.wKey[26] ^ this.X2, this.wKey[27] ^ this.X3 );
            this.LT();
            this.Sb7( this.wKey[28] ^ this.X0, this.wKey[29] ^ this.X1, this.wKey[30] ^ this.X2, this.wKey[31] ^ this.X3 );
            this.LT();
            this.Sb0( this.wKey[32] ^ this.X0, this.wKey[33] ^ this.X1, this.wKey[34] ^ this.X2, this.wKey[35] ^ this.X3 );
            this.LT();
            this.Sb1( this.wKey[36] ^ this.X0, this.wKey[37] ^ this.X1, this.wKey[38] ^ this.X2, this.wKey[39] ^ this.X3 );
            this.LT();
            this.Sb2( this.wKey[40] ^ this.X0, this.wKey[41] ^ this.X1, this.wKey[42] ^ this.X2, this.wKey[43] ^ this.X3 );
            this.LT();
            this.Sb3( this.wKey[44] ^ this.X0, this.wKey[45] ^ this.X1, this.wKey[46] ^ this.X2, this.wKey[47] ^ this.X3 );
            this.LT();
            this.Sb4( this.wKey[48] ^ this.X0, this.wKey[49] ^ this.X1, this.wKey[50] ^ this.X2, this.wKey[51] ^ this.X3 );
            this.LT();
            this.Sb5( this.wKey[52] ^ this.X0, this.wKey[53] ^ this.X1, this.wKey[54] ^ this.X2, this.wKey[55] ^ this.X3 );
            this.LT();
            this.Sb6( this.wKey[56] ^ this.X0, this.wKey[57] ^ this.X1, this.wKey[58] ^ this.X2, this.wKey[59] ^ this.X3 );
            this.LT();
            this.Sb7( this.wKey[60] ^ this.X0, this.wKey[61] ^ this.X1, this.wKey[62] ^ this.X2, this.wKey[63] ^ this.X3 );
            this.LT();
            this.Sb0( this.wKey[64] ^ this.X0, this.wKey[65] ^ this.X1, this.wKey[66] ^ this.X2, this.wKey[67] ^ this.X3 );
            this.LT();
            this.Sb1( this.wKey[68] ^ this.X0, this.wKey[69] ^ this.X1, this.wKey[70] ^ this.X2, this.wKey[71] ^ this.X3 );
            this.LT();
            this.Sb2( this.wKey[72] ^ this.X0, this.wKey[73] ^ this.X1, this.wKey[74] ^ this.X2, this.wKey[75] ^ this.X3 );
            this.LT();
            this.Sb3( this.wKey[76] ^ this.X0, this.wKey[77] ^ this.X1, this.wKey[78] ^ this.X2, this.wKey[79] ^ this.X3 );
            this.LT();
            this.Sb4( this.wKey[80] ^ this.X0, this.wKey[81] ^ this.X1, this.wKey[82] ^ this.X2, this.wKey[83] ^ this.X3 );
            this.LT();
            this.Sb5( this.wKey[84] ^ this.X0, this.wKey[85] ^ this.X1, this.wKey[86] ^ this.X2, this.wKey[87] ^ this.X3 );
            this.LT();
            this.Sb6( this.wKey[88] ^ this.X0, this.wKey[89] ^ this.X1, this.wKey[90] ^ this.X2, this.wKey[91] ^ this.X3 );
            this.LT();
            this.Sb7( this.wKey[92] ^ this.X0, this.wKey[93] ^ this.X1, this.wKey[94] ^ this.X2, this.wKey[95] ^ this.X3 );
            this.LT();
            this.Sb0( this.wKey[96] ^ this.X0, this.wKey[97] ^ this.X1, this.wKey[98] ^ this.X2, this.wKey[99] ^ this.X3 );
            this.LT();
            this.Sb1( this.wKey[100] ^ this.X0, this.wKey[101] ^ this.X1, this.wKey[102] ^ this.X2, this.wKey[103] ^ this.X3 );
            this.LT();
            this.Sb2( this.wKey[104] ^ this.X0, this.wKey[105] ^ this.X1, this.wKey[106] ^ this.X2, this.wKey[107] ^ this.X3 );
            this.LT();
            this.Sb3( this.wKey[108] ^ this.X0, this.wKey[109] ^ this.X1, this.wKey[110] ^ this.X2, this.wKey[111] ^ this.X3 );
            this.LT();
            this.Sb4( this.wKey[112] ^ this.X0, this.wKey[113] ^ this.X1, this.wKey[114] ^ this.X2, this.wKey[115] ^ this.X3 );
            this.LT();
            this.Sb5( this.wKey[116] ^ this.X0, this.wKey[117] ^ this.X1, this.wKey[118] ^ this.X2, this.wKey[119] ^ this.X3 );
            this.LT();
            this.Sb6( this.wKey[120] ^ this.X0, this.wKey[121] ^ this.X1, this.wKey[122] ^ this.X2, this.wKey[123] ^ this.X3 );
            this.LT();
            this.Sb7( this.wKey[124] ^ this.X0, this.wKey[125] ^ this.X1, this.wKey[126] ^ this.X2, this.wKey[sbyte.MaxValue] ^ this.X3 );
            Pack.UInt32_To_LE( (uint)(this.wKey[128] ^ this.X0), output, outOff );
            Pack.UInt32_To_LE( (uint)(this.wKey[129] ^ this.X1), output, outOff + 4 );
            Pack.UInt32_To_LE( (uint)(this.wKey[130] ^ this.X2), output, outOff + 8 );
            Pack.UInt32_To_LE( (uint)(this.wKey[131] ^ this.X3), output, outOff + 12 );
        }

        protected override void DecryptBlock( byte[] input, int inOff, byte[] output, int outOff )
        {
            this.X0 = this.wKey[128] ^ (int)Pack.LE_To_UInt32( input, inOff );
            this.X1 = this.wKey[129] ^ (int)Pack.LE_To_UInt32( input, inOff + 4 );
            this.X2 = this.wKey[130] ^ (int)Pack.LE_To_UInt32( input, inOff + 8 );
            this.X3 = this.wKey[131] ^ (int)Pack.LE_To_UInt32( input, inOff + 12 );
            this.Ib7( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[124];
            this.X1 ^= this.wKey[125];
            this.X2 ^= this.wKey[126];
            this.X3 ^= this.wKey[sbyte.MaxValue];
            this.InverseLT();
            this.Ib6( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[120];
            this.X1 ^= this.wKey[121];
            this.X2 ^= this.wKey[122];
            this.X3 ^= this.wKey[123];
            this.InverseLT();
            this.Ib5( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[116];
            this.X1 ^= this.wKey[117];
            this.X2 ^= this.wKey[118];
            this.X3 ^= this.wKey[119];
            this.InverseLT();
            this.Ib4( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[112];
            this.X1 ^= this.wKey[113];
            this.X2 ^= this.wKey[114];
            this.X3 ^= this.wKey[115];
            this.InverseLT();
            this.Ib3( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[108];
            this.X1 ^= this.wKey[109];
            this.X2 ^= this.wKey[110];
            this.X3 ^= this.wKey[111];
            this.InverseLT();
            this.Ib2( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[104];
            this.X1 ^= this.wKey[105];
            this.X2 ^= this.wKey[106];
            this.X3 ^= this.wKey[107];
            this.InverseLT();
            this.Ib1( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[100];
            this.X1 ^= this.wKey[101];
            this.X2 ^= this.wKey[102];
            this.X3 ^= this.wKey[103];
            this.InverseLT();
            this.Ib0( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[96];
            this.X1 ^= this.wKey[97];
            this.X2 ^= this.wKey[98];
            this.X3 ^= this.wKey[99];
            this.InverseLT();
            this.Ib7( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[92];
            this.X1 ^= this.wKey[93];
            this.X2 ^= this.wKey[94];
            this.X3 ^= this.wKey[95];
            this.InverseLT();
            this.Ib6( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[88];
            this.X1 ^= this.wKey[89];
            this.X2 ^= this.wKey[90];
            this.X3 ^= this.wKey[91];
            this.InverseLT();
            this.Ib5( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[84];
            this.X1 ^= this.wKey[85];
            this.X2 ^= this.wKey[86];
            this.X3 ^= this.wKey[87];
            this.InverseLT();
            this.Ib4( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[80];
            this.X1 ^= this.wKey[81];
            this.X2 ^= this.wKey[82];
            this.X3 ^= this.wKey[83];
            this.InverseLT();
            this.Ib3( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[76];
            this.X1 ^= this.wKey[77];
            this.X2 ^= this.wKey[78];
            this.X3 ^= this.wKey[79];
            this.InverseLT();
            this.Ib2( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[72];
            this.X1 ^= this.wKey[73];
            this.X2 ^= this.wKey[74];
            this.X3 ^= this.wKey[75];
            this.InverseLT();
            this.Ib1( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[68];
            this.X1 ^= this.wKey[69];
            this.X2 ^= this.wKey[70];
            this.X3 ^= this.wKey[71];
            this.InverseLT();
            this.Ib0( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[64];
            this.X1 ^= this.wKey[65];
            this.X2 ^= this.wKey[66];
            this.X3 ^= this.wKey[67];
            this.InverseLT();
            this.Ib7( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[60];
            this.X1 ^= this.wKey[61];
            this.X2 ^= this.wKey[62];
            this.X3 ^= this.wKey[63];
            this.InverseLT();
            this.Ib6( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[56];
            this.X1 ^= this.wKey[57];
            this.X2 ^= this.wKey[58];
            this.X3 ^= this.wKey[59];
            this.InverseLT();
            this.Ib5( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[52];
            this.X1 ^= this.wKey[53];
            this.X2 ^= this.wKey[54];
            this.X3 ^= this.wKey[55];
            this.InverseLT();
            this.Ib4( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[48];
            this.X1 ^= this.wKey[49];
            this.X2 ^= this.wKey[50];
            this.X3 ^= this.wKey[51];
            this.InverseLT();
            this.Ib3( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[44];
            this.X1 ^= this.wKey[45];
            this.X2 ^= this.wKey[46];
            this.X3 ^= this.wKey[47];
            this.InverseLT();
            this.Ib2( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[40];
            this.X1 ^= this.wKey[41];
            this.X2 ^= this.wKey[42];
            this.X3 ^= this.wKey[43];
            this.InverseLT();
            this.Ib1( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[36];
            this.X1 ^= this.wKey[37];
            this.X2 ^= this.wKey[38];
            this.X3 ^= this.wKey[39];
            this.InverseLT();
            this.Ib0( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[32];
            this.X1 ^= this.wKey[33];
            this.X2 ^= this.wKey[34];
            this.X3 ^= this.wKey[35];
            this.InverseLT();
            this.Ib7( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[28];
            this.X1 ^= this.wKey[29];
            this.X2 ^= this.wKey[30];
            this.X3 ^= this.wKey[31];
            this.InverseLT();
            this.Ib6( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[24];
            this.X1 ^= this.wKey[25];
            this.X2 ^= this.wKey[26];
            this.X3 ^= this.wKey[27];
            this.InverseLT();
            this.Ib5( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[20];
            this.X1 ^= this.wKey[21];
            this.X2 ^= this.wKey[22];
            this.X3 ^= this.wKey[23];
            this.InverseLT();
            this.Ib4( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[16];
            this.X1 ^= this.wKey[17];
            this.X2 ^= this.wKey[18];
            this.X3 ^= this.wKey[19];
            this.InverseLT();
            this.Ib3( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[12];
            this.X1 ^= this.wKey[13];
            this.X2 ^= this.wKey[14];
            this.X3 ^= this.wKey[15];
            this.InverseLT();
            this.Ib2( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[8];
            this.X1 ^= this.wKey[9];
            this.X2 ^= this.wKey[10];
            this.X3 ^= this.wKey[11];
            this.InverseLT();
            this.Ib1( this.X0, this.X1, this.X2, this.X3 );
            this.X0 ^= this.wKey[4];
            this.X1 ^= this.wKey[5];
            this.X2 ^= this.wKey[6];
            this.X3 ^= this.wKey[7];
            this.InverseLT();
            this.Ib0( this.X0, this.X1, this.X2, this.X3 );
            Pack.UInt32_To_LE( (uint)(this.X0 ^ this.wKey[0]), output, outOff );
            Pack.UInt32_To_LE( (uint)(this.X1 ^ this.wKey[1]), output, outOff + 4 );
            Pack.UInt32_To_LE( (uint)(this.X2 ^ this.wKey[2]), output, outOff + 8 );
            Pack.UInt32_To_LE( (uint)(this.X3 ^ this.wKey[3]), output, outOff + 12 );
        }
    }
}
